name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add clippy rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features
      - run: cargo doc
      - run: cargo test --all-features
      - run: cargo test --all-features --examples
